nodeLinker: node-modules

packageExtensions:
  "@trezor/device-authenticity@*":
    dependencies:
      tslib: "*"

  "@trezor/connect@*":
    dependencies:
      typescript: "*"

  "@trezor/blockchain-link@*":
    dependencies:
      typescript: "*"

  "@solana-program/token-2022@*":
    peerDependenciesMeta:
      "@solana/sysvars":
        optional: true

  "@solana/codecs-strings@*":
    peerDependenciesMeta:
      fastestsmallesttextencoderdecoder:
        optional: true

  "@solana/rpc-subscriptions-channel-websocket@*":
    peerDependenciesMeta:
      ws:
        optional: true

  "debug@*":
    peerDependenciesMeta:
      "@types/supports-color":
        optional: true
