token:
  name: COVENAN Token Test 1
  symbol: CNT-T1
  maxSupply: 35000
mint:
  to: ''
  amount: 35000
burn:
  contractAddress: '0xd9d7a3ae5fdf5c81815635dade85df19830e2ad8'
  from: ''
  amount: 35000
deployedAt:
  sepolia: ''
  mainnet: '2026-06-12'
